apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.secureConnections.required }}
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: https
    {{- else }}
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    {{- end }}
    - port: 7918
      targetPort: 7918
      protocol: TCP
      name: jms
    - port: 7919
      targetPort: 7919
      protocol: TCP
      name: wss
  selector:
    app: {{ template "fullname" . }}
  sessionAffinity: ClientIP
