apiVersion: v1
kind: Service
metadata:
  name: application-api
  labels:
    app.kubernetes.io/name: {{ include "velocity.name" . }}-application-api
    helm.sh/chart: {{ include "velocity.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: application-api-port
      protocol: TCP
      port: 3499
      targetPort: 3499
  selector:
    app.kubernetes.io/name: {{ include "velocity.name" . }}-application-api
    app.kubernetes.io/instance: {{ .Release.Name }}