apiVersion: v1
kind: Service
metadata:
  name: continuous-release-consumer
  labels:
    app.kubernetes.io/name: {{ include "velocity.name" . }}-continuous-release-consumer
    helm.sh/chart: {{ include "velocity.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: continuous-release-consumer-port
      protocol: TCP
      port: 3411
      targetPort: 3411
  selector:
    app.kubernetes.io/name: {{ include "velocity.name" . }}-continuous-release-consumer
    app.kubernetes.io/instance: {{ .Release.Name }}
