apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "velocity.fullname" . }}-continuous-release-consumer
  labels:
    app.kubernetes.io/name: {{ include "velocity.name" . }}-continuous-release-consumer
    helm.sh/chart: {{ include "velocity.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "velocity.name" . }}-continuous-release-consumer
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "velocity.name" . }}-continuous-release-consumer
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- include "pod.imagePullSecrets" . | indent 6 }}
      containers:
        - name: continuous-release-consumer
          image: '{{ .Values.images.continuous_release_consumer }}'
          imagePullPolicy: Always
          ports:
            - containerPort: 3411
          env:
            - name: NODE_ENV
              value: onprem
            - name: PORT
              value: '3411'
            - name: LOG_LEVEL
              value: '{{ .Values.loglevel }}'
            - name: API_TOKEN
              value: '{{ .Values.apitoken }}'
            - name: CIPHER_KEY
              value: '{{ .Values.ciphertoken }}'
            - name: HMAC_KEY
              value: '{{ .Values.hmackey }}'
            - name: AMQP_URL
              value: {{ include "rabbitmq.url" . }}
            - name: BRANDING
              value: HCL
