apiVersion: v1
kind: Service
metadata:
  name: multi-app-pipeline-api
  labels:
    app.kubernetes.io/name: {{ include "velocity.name" . }}-multi-app-pipeline-api
    helm.sh/chart: {{ include "velocity.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: multi-app-pipeline-api-port
      protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    app.kubernetes.io/name: {{ include "velocity.name" . }}-multi-app-pipeline-api
    app.kubernetes.io/instance: {{ .Release.Name }}
