apiVersion: v1
kind: Service
metadata:
  name: release-events-ui
  labels:
    app.kubernetes.io/name: {{ include "velocity.name" . }}-release-events-ui
    helm.sh/chart: {{ include "velocity.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: release-events-ui-port
      protocol: TCP
      port: 3010
      targetPort: 3010
  selector:
    app.kubernetes.io/name: {{ include "velocity.name" . }}-release-events-ui
    app.kubernetes.io/instance: {{ .Release.Name }}
