apiVersion: v1
kind: Service
metadata:
  name: release-events-api
  labels:
    app.kubernetes.io/name: {{ include "velocity.name" . }}-release-events-api
    helm.sh/chart: {{ include "velocity.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: release-events-api-port
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ include "velocity.name" . }}-release-events-api
    app.kubernetes.io/instance: {{ .Release.Name }}
