apiVersion: v1
kind: Service
metadata:
  name: reporting-ui
  labels:
    app.kubernetes.io/name: {{ include "velocity.name" . }}-reporting-ui
    helm.sh/chart: {{ include "velocity.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: reporting-ui-port
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/name: {{ include "velocity.name" . }}-reporting-ui
    app.kubernetes.io/instance: {{ .Release.Name }}
