apiVersion: v1
kind: Service
metadata:
  name: security-api
  labels:
    app.kubernetes.io/name: {{ include "velocity.name" . }}-security-api
    helm.sh/chart: {{ include "velocity.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: security-api-port
      protocol: TCP
      port: 3911
      targetPort: 3911
  selector:
    app.kubernetes.io/name: {{ include "velocity.name" . }}-security-api
    app.kubernetes.io/instance: {{ .Release.Name }}
