apiVersion: v1
kind: Service
metadata:
  name: {{ include "velocity.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "velocity.name" . }}
    helm.sh/chart: {{ include "velocity.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ include "velocity.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
