apiVersion: v1
kind: Service
metadata:
  name: velocity-rabbitmq
  labels:
    app.kubernetes.io/name: {{ include "velocity.name" . }}-rabbitmq
    helm.sh/chart: {{ include "velocity.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - name: epmd
    port: 4369
    targetPort: epmd
  - name: amqp
    port: 5672
    targetPort: amqp
    # nodePort: {{ .Values.rabbitmq.nodePort }}
  - name: dist
    port: {{ .Values.rabbitmq.nodePort | add 20000 }}
    targetPort: dist
  - name: stats
    port: {{ .Values.rabbitmq.managerPort }}
    targetPort: stats
  selector:
    app.kubernetes.io/name: {{ include "velocity.name" . }}-rabbitmq
    app.kubernetes.io/instance: {{ .Release.Name }}
